# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import image_search_pb2 as image__search__pb2


class ImageSearchServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SearchImage = channel.unary_unary(
                '/image_search.ImageSearchService/SearchImage',
                request_serializer=image__search__pb2.ImageRequest.SerializeToString,
                response_deserializer=image__search__pb2.ImageResponse.FromString,
                )


class ImageSearchServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SearchImage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ImageSearchServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SearchImage': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchImage,
                    request_deserializer=image__search__pb2.ImageRequest.FromString,
                    response_serializer=image__search__pb2.ImageResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'image_search.ImageSearchService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ImageSearchService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SearchImage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/image_search.ImageSearchService/SearchImage',
            image__search__pb2.ImageRequest.SerializeToString,
            image__search__pb2.ImageResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
