# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: image_search.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12image_search.proto\x12\x0cimage_search\"\x1f\n\x0cImageRequest\x12\x0f\n\x07keyword\x18\x01 \x01(\t\"#\n\rImageResponse\x12\x12\n\nimage_data\x18\x01 \x01(\x0c\x32\\\n\x12ImageSearchService\x12\x46\n\x0bSearchImage\x12\x1a.image_search.ImageRequest\x1a\x1b.image_search.ImageResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'image_search_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_IMAGEREQUEST']._serialized_start=36
  _globals['_IMAGEREQUEST']._serialized_end=67
  _globals['_IMAGERESPONSE']._serialized_start=69
  _globals['_IMAGERESPONSE']._serialized_end=104
  _globals['_IMAGESEARCHSERVICE']._serialized_start=106
  _globals['_IMAGESEARCHSERVICE']._serialized_end=198
# @@protoc_insertion_point(module_scope)
